name: Laravel CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: ffe_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivamathur/setup-php@v2
      with:
        php-version: 8.2.15
        extensions: mbstring, mysql, xml, ctype
        coverage: none
    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --legacy-peer-deps
    
    - name: Set up Laravel environment
      run: |
        cp .env.example .env
        php artisan key:generate
      
    # - name: Run migrations
    #   run: php artisan migrate

    - name: Execute tests
      run: php artisan test

